// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enevjiodbmngnkwkwuud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuZXZqaW9kYm1uZ25rd2t3dXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NjAwNDksImV4cCI6MjA3NDMzNjA0OX0.S32V7VzipElYgj8l21-xMMEji6fcnAloBYuOAjERz-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});